using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.0.0.999")]
[assembly: AssemblyFileVersionAttribute("0.0.0.999")]
[assembly: AssemblyCopyrightAttribute("Copyright 2013-2015")]
[assembly: AssemblyProductAttribute("Iteration0")]
[assembly: AssemblyCompanyAttribute("ClearMeasure")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.999")]
